#############
# Dockerfile to build container image for Facs BLOOM filtering tool
# See Docs and Source code at: https://github.com/SciLifeLab/facs
#
# Build docker image:  docker build -t facs  -f ./Dockerfile.facs-bloom .
#
# Run docker container: docker run -it --rm -v ${PWD}:${PWD} --entrypoint /bin/bash  facs:latest
#
# use facs like:
#  * build BLOOM filter db:  "facs build -r Cotton.contaminants.fa"
#  * clean NGS short reads:  "facs -t 0.2 remove -r facs.bloom.idx  -q my_reads.fastq -o ./out_dir | json_reformat"
#      this produces an easy to read report in table format (after parsing the json format)
#############

# See https://hub.docker.com/_/gcc/ for other versions of GCC container
# FROM gcc:10.4.0 as builder-stage
# FROM public.ecr.aws/docker/library/gcc:15-trixie as builder-stage # (TOO NEW)
ARG PLATFORM="linux/amd64"
FROM --platform=${PLATFORM}  public.ecr.aws/docker/library/gcc:11.5.0  AS builder-stage

LABEL description="FACS BLOOM tool for filtering NGS read files against a BLOOM filter database"
LABEL org.opencontainers.image.authors="mauricio.larota@corteva.com"


# The building of the c++ code may be done outside of this image as part of gitlab's CI/CD...(See other examples in my gitlab page)
# If that's the case, just copy the newly built tools from the ./bin dir to absolute path /bin of image
# COPY ./bin/facs /bin/facs

# Else, the source code for FACS bloom filter at : git clone https://github.com/SciLifeLab/facs
##
# OR Download source code from "https://github.com/SciLifeLab/facs/archive/refs/heads/master.zip && unzip master.zip"
# build FACS
WORKDIR /build-dir
# RUN cd /build-dir && wget https://github.com/SciLifeLab/facs/archive/refs/heads/master.zip  \
RUN cd /build-dir && wget https://github.com/maol-corteva/facs/archive/refs/heads/master.zip  \
    && unzip master.zip \
    && cd facs-master/facs \
    && make all \
    && cp -v ./facs  /bin/facs \
    && chmod -fv a+x /bin/facs

# build SeqTK version release 1.3  (keeping to a stable release)
RUN cd /build-dir && wget https://github.com/lh3/seqtk/archive/refs/tags/v1.3.zip  \
    && unzip v1.3.zip \
    && cd seqtk-1.3 \
    && make \
    && cp -v ./seqtk /bin/seqtk \
    && chmod -fv a+x /bin/seqtk \
    && cd / && rm -r /build-dir

FROM ubuntu:20.04 AS facs-bloom
ARG DEBIAN_FRONTEND="noninteractive"
ARG TZ="UTC"
ENV TZ="${TZ}"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
USER root

# RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 871920D1991BC93C

RUN apt-get update && apt-get install -y --no-install-recommends \
    gzip \
    ca-certificates \
    # get json_reformat tool included in yajl ubuntu apt pck.
    yajl-tools \
    && apt-get clean && rm -rf /var/lib/apt/lists/* && update-ca-certificates

# Set run user/group as uid 2000 gid 3000 for use in KubeFarm
ARG USER=appuser
ARG USERGROUP=appgroup
ARG myUID=2000
ARG myGID=3000
RUN groupadd -r -g ${myGID} ${USERGROUP}  &&  useradd -g ${myGID} --uid=${myUID} ${USER} \
    && echo creating user "${USER}:${USERGROUP} -> ${myUID}:${myGID}"

# RUN groupadd -r -g ${myGID} ${USERGROUP} \
#     && echo creating user "${USER}:${USERGROUP} > ${myUID}:${myGID}" \
#     && useradd -m -d /home/${USER} -s /bin/bash -g ${myGID} --uid=${myUID} -G sudo ${USER} \
#     && echo "${USER}:${USER}" | chpasswd \
#     && usermod -aG sudo ${USER}


WORKDIR /app
# Get app from previous build stage (include required openmp lib)
COPY --from=builder-stage --chown=${myUID}:${myGID} /bin/facs /app/
COPY --from=builder-stage --chown=${myUID}:${myGID} /bin/seqtk /app/
COPY --from=builder-stage /usr/local/lib64/libgomp.so.1.0.0  /lib/x86_64-linux-gnu/libgomp.so.1
# copy a demo bloom DB (maize B73 biased) from host filesystem
COPY facs_bloom_filters/Zm.contaminants.rRNA.C.M.ITS1z.bloom  /app/contaminant_bloom_filters/Zm.contaminants.rRNA.C.M.ITS1z.bloom

# USER appuser:appgroup
USER ${myUID}:${myGID}

ENV PATH=${PATH}:/app

# Set OpenMP default number of CPUs for multithreading (used by facs)
ARG OMP_NUM_THREADS=8
ENV OMP_NUM_THREADS=${OMP_NUM_THREADS}
ENV CPU_THREADS=${OMP_NUM_THREADS:-8}

# default entrypoint when image is executed..
ENTRYPOINT ["/app/facs"]
