#############
# Dockerfile to build container image for Facs BLOOM filtering tool
# See Original Docs and Source code at: https://github.com/SciLifeLab/facs
# A recent fork with modifications is at: https://github.com/maol-corteva/facs
# We will be using this new FORK for building the container image but the executable will still be called "facs"
#
# Build docker image:  docker build -t corteva-facs  -f ./Dockerfile.facs-bloom .
#
# Run docker container: docker run -it --rm -v ${PWD}:${PWD} --entrypoint /bin/bash  corteva-facs:latest
#
# use facs like:
#  * build BLOOM filter db:  "facs build -r Cotton.contaminants.fa"
#  * clean NGS short reads:  "facs -t 0.2 remove -r facs.bloom.idx  -q my_reads.fastq -o ./out_dir | json_reformat"
#      this produces an easy to read report in table format (after parsing the json format)
#############


###################################
# See https://hub.docker.com/_/gcc/ for other versions of GCC container
# FROM gcc:10.4.0 as builder-stage
# FROM public.ecr.aws/docker/library/gcc:15-trixie as builder-stage # (TOO NEW)
ARG PLATFORM="linux/amd64"
FROM --platform=${PLATFORM}  public.ecr.aws/docker/library/gcc:11.5.0  AS builder-stage

LABEL description="FACS BLOOM tool for filtering NGS read files against a BLOOM filter database"
LABEL org.opencontainers.image.authors="mauricio.larota@corteva.com"


# The source code for "forked" FACS bloom filter at : git clone https://github.com/maol-corteva/facs

# Download source code from https://github.com/maol-corteva/facs/archive/refs/heads/master.zip  && unzip master.zip
# build FACS
WORKDIR /build-dir
RUN cd /build-dir && wget https://github.com/maol-corteva/facs/archive/refs/heads/master.zip  \
    && unzip master.zip \
    && cd facs-master/facs \
    && make all \
    && cp -v ./facs  /bin/facs \
    && chmod -fv a+x /bin/facs

# build SeqTK version release 1.3  (keeping to a stable release)
RUN cd /build-dir && wget https://github.com/lh3/seqtk/archive/refs/tags/v1.3.zip  \
    && unzip v1.3.zip \
    && cd seqtk-1.3 \
    && make \
    && cp -v ./seqtk /bin/seqtk \
    && chmod -fv a+x /bin/seqtk \
    && cd / && rm -r /build-dir



###################################
FROM --platform=${PLATFORM} public.ecr.aws/lts/ubuntu:22.04 AS facs-bloom
ARG DEBIAN_FRONTEND="noninteractive"
ARG TZ="UTC"
ENV TZ="${TZ}"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
USER root
# Install runtime dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gzip \
    ca-certificates \
    # get json_reformat tool included in yajl ubuntu apt pck.
    yajl-tools \
    libgomp1 \
    && apt-get clean && rm -rf /var/lib/apt/lists/* && update-ca-certificates

# Set run user/group as uid 2000 gid 3000 for use in KubeFarm
ARG USER=appuser
ARG USERGROUP=appgroup
ARG myUID=2000
ARG myGID=3000
RUN groupadd -r -g ${myGID} ${USERGROUP}  &&  useradd -g ${myGID} --uid=${myUID} ${USER} \
    && echo creating user "${USER}:${USERGROUP} -> ${myUID}:${myGID}"

# RUN groupadd -r -g ${myGID} ${USERGROUP} \
#     && echo creating user "${USER}:${USERGROUP} > ${myUID}:${myGID}" \
#     && useradd -m -d /home/${USER} -s /bin/bash -g ${myGID} --uid=${myUID} -G sudo ${USER} \
#     && echo "${USER}:${USER}" | chpasswd \
#     && usermod -aG sudo ${USER}


WORKDIR /app
# Get app from previous build stage (include required openmp lib)
COPY --from=builder-stage --chown=${myUID}:${myGID} /bin/facs /app/
COPY --from=builder-stage --chown=${myUID}:${myGID} /bin/seqtk /app/
# After system install... replace with original libgomp to avoid issues
RUN rm -f /lib/x86_64-linux-gnu/libgomp.so.1 
COPY --from=builder-stage /usr/local/lib64/libgomp.so.1.0.0  /lib/x86_64-linux-gnu/libgomp.so.1

# copy a demo bloom DB from host filesystem
COPY facs_bloom_filters/*  /app/contaminant_bloom_filters/

# USER appuser:appgroup
USER ${myUID}:${myGID}

ENV PATH=${PATH}:/app

# Set OpenMP default number of CPUs for multithreading (used by facs)
ARG OMP_NUM_THREADS=8
ENV OMP_NUM_THREADS=${OMP_NUM_THREADS}
ENV CPU_THREADS=${OMP_NUM_THREADS:-8}

# default entrypoint when image is executed..
ENTRYPOINT ["/app/facs"]
